/**
 * Domain types for Yeongsujeung.
 *
 * These are the application-level types. Database row types live in
 * `database.ts` (auto-generated by `pnpm db:types`). When you query the
 * DB, transform DB rows into these domain types in the queries layer.
 */

export type Locale = 'en' | 'ko' | 'de';

export type ReceiptStatus = 'pending' | 'processing' | 'extracted' | 'failed';

export type CategorySlug =
  | 'restaurant'
  | 'cafe'
  | 'convenience'
  | 'grocery'
  | 'transport'
  | 'subscription'
  | 'school'
  | 'health'
  | 'other';

export interface Category {
  id: string;
  slug: string;
  nameEn: string;
  nameKo: string;
  icon: string | null;
  color: string | null;
  isSystem: boolean;
  sortOrder: number;
}

export interface ReceiptItem {
  id: string;
  receiptId: string;
  name: string;
  quantity: number;
  unitPrice: number | null;
  totalPrice: number | null;
  sortOrder: number;
}

export interface Receipt {
  id: string;
  userId: string;
  categoryId: string | null;
  imagePath: string;
  imageUrl: string | null;
  vendor: string | null;
  totalAmount: number | null;
  taxAmount: number | null;
  currency: string;
  purchasedAt: Date | null;
  status: ReceiptStatus;
  errorMessage: string | null;
  userNotes: string | null;
  isFlagged: boolean;
  createdAt: Date;
  updatedAt: Date;
  items?: ReceiptItem[];
  category?: Category | null;
}

export interface User {
  id: string;
  email: string;
  displayName: string | null;
  locale: Locale;
  currency: string;
  createdAt: Date;
}
